USE [master]
GO
/****** Object:  Database [Bookkeeper]    Script Date: 15/08/2021 10:50:38 PM ******/
CREATE DATABASE [Bookkeeper]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Bookkeeper', FILENAME = N'/var/opt/mssql/data/Bookkeeper.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Bookkeeper_log', FILENAME = N'/var/opt/mssql/data/Bookkeeper_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Bookkeeper] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
	EXEC [Bookkeeper].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Bookkeeper] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Bookkeeper] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Bookkeeper] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Bookkeeper] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Bookkeeper] SET ARITHABORT OFF 
GO
ALTER DATABASE [Bookkeeper] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Bookkeeper] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Bookkeeper] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Bookkeeper] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Bookkeeper] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Bookkeeper] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Bookkeeper] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Bookkeeper] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Bookkeeper] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Bookkeeper] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Bookkeeper] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Bookkeeper] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Bookkeeper] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Bookkeeper] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Bookkeeper] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Bookkeeper] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Bookkeeper] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Bookkeeper] SET RECOVERY FULL 
GO
ALTER DATABASE [Bookkeeper] SET  MULTI_USER 
GO
ALTER DATABASE [Bookkeeper] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Bookkeeper] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Bookkeeper] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Bookkeeper] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Bookkeeper] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Bookkeeper] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Bookkeeper', N'ON'
GO
ALTER DATABASE [Bookkeeper] SET QUERY_STORE = OFF
GO
USE [Bookkeeper]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 15/08/2021 10:50:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books]
(
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	CONSTRAINT [PK_Books] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookSnapshots]    Script Date: 15/08/2021 10:50:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookSnapshots]
(
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BookId] [bigint] NOT NULL,
	[Version] [bigint] NOT NULL,
	[Value] [decimal](8, 2) NOT NULL,
	CONSTRAINT [PK_BookSnapshots] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TransactionEvents]    Script Date: 15/08/2021 10:50:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TransactionEvents]
(
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[BookId] [bigint] NOT NULL,
	[Version] [bigint] NOT NULL,
	[Type] [tinyint] NOT NULL,
	[Value] [decimal](8, 2) NOT NULL,
	[Occurred] [datetimeoffset](0) NOT NULL,
	CONSTRAINT [PK_TransactionEvents] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [Index_BookId_Version_Snapshot]    Script Date: 15/08/2021 10:50:38 PM ******/
CREATE NONCLUSTERED INDEX [Index_BookId_Version_Snapshot] ON [dbo].[BookSnapshots]
(
	[BookId] ASC,
	[Version] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [TransactionEvents_BookId_Version_Index]    Script Date: 15/08/2021 10:50:38 PM ******/
CREATE NONCLUSTERED INDEX [TransactionEvents_BookId_Version_Index] ON [dbo].[TransactionEvents]
(
	[BookId] ASC,
	[Version] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Bookkeeper] SET  READ_WRITE 
GO
